### PR TITLE
Add outline to mermaid objects

### PR DESCRIPTION
**Pull request by ire4ever1190**
Adds outline to shapes in mermaid diagrams so that shapes can be better told apart

e.g. for this diagram
```
flowchart LR
  A(((A))) -->|a|B((B))
  ID[(Database)]
```
```mermaid
flowchart LR
  A(((A))) -->|a|B((B))
  ID[(Database)]
```

Currently it looks like this 
image

Main issue is that double circles cant be easily told apart from single circles (which is important when drawing FSM diagrams)

After this PR it looks like this 

image

Which better highlights the shapes and matches the normal mermaid diagrams more.

Not too sure what the outline colour should be so don't mind changing it to something else

### CODE REVIEW

**Comment by insanum** [comment]
This theme has been rewritten for Obsidian 0.16.
When you get access to the latest, can you please update and retest your changes?

**Comment by ire4ever1190** [comment]
Retested changes, outline still appears and doesn't seem to affect anything else

**Comment by insanum** [comment]
Did you know that the same issue exists with the default theme? Would it be better to get this addressed in Obsidian and then all themes would benefit (i.e., probably via a common variable)? There are other mermaid specific issue like this also seen in the default theme.

**Comment by ire4ever1190** [comment]
Sorry thought it existed in default theme, think I might've just left the CSS snippet enabled.

Will close this and raise issue on obsidian's bug tracker

**Pull request closed without merging**
